<div>
    <table>
        <tr>
            <td>Usernmae</td>
            <td>Password</td>
        </tr>
        <tr>
            <td>{{.mysqluser}}</td>
            <td>{{.mysqlpass}}</td>
        </tr>
    </table>
</div>